### ISSUE TITLE
Podman machine type is not visible on Windows 

### ISSUE THREAD

**Issue by gastoner** [podman-desktop/podman-desktop#10191]
### Bug description

I don't see either WSL or HyperV when I run the installer from main:
![Image](https://github.com/user-attachments/assets/b51f1c8c-eef2-4bcf-b16d-2c5bd4e684a4)

When I run `pnpm watch`: 
![Image](https://github.com/user-attachments/assets/b6032ed0-e731-4349-9fea-5a25a2866254)

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

From the main, run `pnpm compile --win nsis` and run created installer
Assert that the VM type is missing 

### Relevant log output

```shell

```

**Comment by amisskii** [comment]
I was not able to reproduce this issue

**Comment by jeffmaury** [comment]
You need to run in elevated mode for HyperV

**Comment by gastoner** [comment]
Closing, I've had some problems with my Windows machine which caused this
