### ISSUE TITLE
Add extension API which allow to open http links

### ISSUE THREAD

**Issue by evidolob** [podman-desktop/podman-desktop#1891]
### Is your enhancement related to a problem? Please describe

It could be useful to open k8s/openshift console from extension command, to do so, extension should have ability to open http url.

### Describe the solution you'd like

API could be similar to vscode one:

```typescript        
namespace env {
/**
* Open URL in default system application
*/
export function openExternal(target: Uri): Thenable<boolean>;
}
```

**Comment by evidolob** [comment]
cc @gbraad

**Comment by dgolovin** [comment]
Do extensions prohibited to use 'shell' module?
Would code below work?

```
import { shell } from 'electron';

shell.openExternal(url);
```

**Comment by benoitf** [comment]
@dgolovin it should not be used
Also it would mean that your extension depends on Electron.
