### ISSUE TITLE
Mutliple same options (Push image to kind cluster) in kebab menu over image item - caused by Kind extenions activation/deactivation process

### ISSUE THREAD

**Issue by odockal** [podman-desktop/podman-desktop#2069]
### Bug description

![Screenshot_20230413_152444](https://user-images.githubusercontent.com/19164299/231777019-76b5700d-bb59-447b-966b-447566c9674d.png)

### Operating system

Fedora 37

### Version

next (development version)

### Steps to reproduce

One needs to probably have kind installed on PD. Then when Kind extension is activated/deactivated in Settings -> Extensions, another context menu item (Push image to Kind) is added. Extensions Activation/Deactivation call is not cleaning up properly.

**Comment by deboer-tim** [comment]
FWIW I have seen this (and multiple Kind buttons on the status bar) when making changes to the Kind extension while doing `yarn watch`, would be good to confirm that's not the case here.

**Comment by benoitf** [comment]
I think the kind extension is not cleaning up (disposing the action) on deactivate so yes, each time extension is reloaded it'll add again a new entry

**Comment by benoitf** [comment]
but a fresh start shouldn't show that

**Comment by odockal** [comment]
@benoitf you are right. Kind extension activation/deactivation does that. If I do it from _Settings -> Extensions -> Kind: Activate/deactivate_, I get into a  state where the number of context menu items over image is growing by the number of activations/deactivation cycles. On windows it is the same.

**Comment by deboer-tim** [comment]
Ah. Since that isn't development time related we should fix. Let's use this issue to track having Kind extension cleanup correctly.
