### ISSUE TITLE
New install: Error: Error: spawn podman ENOENT

### ISSUE THREAD

**Issue by ed-randall-blk** [podman-desktop/podman-desktop#2650]
### Issue Description

First-time user of podman today.
Downloaded podman-desktop-1.0.1-universal.dmg, clicked, dragged to Applications.
Opened it, wondered where to start, seems I need to create a Podman machine;
Settings > Create a Podman machine
Name: podman-machine-default
CPU(s): 4
Memory: 8GB
Disk size: 80.05GB (became a little irritated by this, too fine-grained, it's impossible to choose a round number)
Image Path (Optional)(: left it blank initially
Machine with root privileges: I don't know, left it off initially
Create

Error: Error: spawn podman ENOENT

???
Show Logs:
Error:Error: spawn podman: ENOENT

Clearly it can't create something, try the "Machine with root privileges" switch?
- No change

Maybe that optional image path?
Browse...
There's no option to create a new dir on the file chooser
Manually create a dir for this in my homedir
Choose it - doesn't let me actually choose.  Does it want a file? No clues.  The blue "Open" button goes to grey and the dialog doesn't dismiss.
Cancel
???

OK, RTFM.
Ah, seems I somehow skipped a step to install the podman cli.   If I rewind it seems I was warned about that earlier but somehow missed it in the excitement.    The above is a basic beginners usability issue - the settings could help by telling me "You still havn't installed the podman-cli, idiot!"

### Steps to reproduce the issue

Steps to reproduce the issue
see above

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected
well some kind of get me going into a rancher/docker-desktop-type situation where I can run containers would be nice?

### podman info output

```yaml
Darwin 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64

podman desktop 1.0.1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Sounds like you are using podman-desktop and this seems to be a problem with podman-desktop  so I move this over to the desktop repo.

cc @benoitf

**Comment by benoitf** [comment]
Hello @ed-randall-blk thanks for your report.

it looks like you're reporting irritating issues as well your bigger issue around podman not being found.

> Disk size: 80.05GB (became a little irritated by this, too fine-grained, it's impossible to choose a round number)

You can follow https://github.com/containers/podman-desktop/issues/2319 we are aware and will enhance it.

Then about 'podman NOENT', yes you need to install Podman first (you should see a screen on the dasboard)

And of course you shouldn't be able to create a Podman Machine if podman is not installed
This is tracked as https://github.com/containers/podman-desktop/issues/2553

I will close this issue as AFAIK we already have open issues but please feel to comment on these existing issues or report new problem you're facing as feedback is important.
