### ISSUE TITLE
Broken layout when successfully play Pods or Containers from a Kubernetes YAML File

### ISSUE THREAD

**Issue by lstocchi** [podman-desktop/podman-desktop#3117]
### Bug description

![play_yaml_broken_layout](https://github.com/containers/podman-desktop/assets/49404737/ec0770a2-9e18-4f55-aade-bc0655ef7b2d)

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. play kubernetes yaml -> deploy something -> when successfully the page is cut and there is no scrollbar to reach the bottom page

**Comment by benoitf** [comment]
is it a dup of https://github.com/containers/podman-desktop/issues/2621 ?

**Comment by cdrage** [comment]
Yup, https://github.com/containers/podman-desktop/pull/3050 fixes this issue.
