### ISSUE TITLE
Implement Button UI component

### ISSUE THREAD

**Issue by jeffmaury** [podman-desktop/podman-desktop#6896]

**Comment by axel7083** [comment]
## Creating a **reusable** button 

Our current button exposes the following 

https://github.com/containers/podman-desktop/blob/de550a1603140de23c6a91d03b152ecf62c6834f/packages/renderer/src/lib/ui/Button.svelte#L10-L16

## Some remarks

### `hidden` property

The hidden property should be removed, as we are already passing down the classes. If a parent need to hide the button it should uses the following

```ts
<Button class:hidden={true}>....</Button>
```

### Links

IMO We should expose a `href` property as we often in some extension implement our own button.

See https://flowbite-svelte.com/docs/components/buttons#References for examples

### Icons / loading

IMO We should include two component, `Button` and `IconButton`.

Most component libraries does not make the icons a property for a low component such as button. 

<img width="416" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/ef966bb8-f30d-4fd2-a531-40509c34a7dd">

> See https://flowbite-svelte.com/docs/components/buttons#Icon_buttons

<img width="367" alt="image" src="https://github.com/containers/podman-desktop/assets/42176370/52c19c21-01c4-4665-a6fe-f2375219d3e5">

> See https://www.shadcn-svelte.com/docs/components/button#with-icon

## Inspiration

here are some state of the art ui component libraries for examples/references

- https://www.shadcn-svelte.com/ (58,384 downloads/weeks)
- https://flowbite-svelte.com/ (28,939 downloads/weeks)
