### ISSUE TITLE
Display podman version in the machine details

### ISSUE THREAD

**Issue by slemeur** [podman-desktop/podman-desktop#897]
### Is your enhancement related to a problem? Please describe

As a user, I may need to know the version of podman which is currently running in my podman-machine. This could be helpful for debugging purposes

### Describe the solution you'd like

We should display in the details of the machine, what is the running version of podman.

**Comment by afbjorklund** [comment]
Currently it only shows the version of the local podman remote client, and nothing at all for the docker client.

```
Client:
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64

Server:
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.19.7
Built:        Fri Apr 14 17:42:56 2023
OS/Arch:      linux/amd64

```

When the provider is up and running, it would probably be better to show the remote version (same for docker).

```console
$ docker --version
Docker version 24.0.1, build 6802122
```

**Comment by deboer-tim** [comment]
Podman Machine version is now shown in Settings > Resources, closing.
