### ISSUE TITLE
Can't get to Settings without resizing window

### ISSUE THREAD

**Issue by deboer-tim** [podman-desktop/podman-desktop#9948]
### Bug description

The first time I moved up to a build that had text + icons, I couldn't get to Settings without resizing the window:

![Image](https://github.com/user-attachments/assets/76eab904-963e-4184-a0cb-f152acdae67d)

This was fine before, the added height of the text makes it not fit. We had designs a while ago where there was a vertical ... or scroll bars so that Settings is always on the screen, we'll need to revisit.

### Operating system

macOS 15.1

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

Install a few extensions; have a smallish window.

### Relevant log output

```shell

```

**Comment by benoitf** [comment]
it's a dup of https://github.com/podman-desktop/podman-desktop/issues/6774 so closing this one
